{"uuid":"50023160-92d5-4ac1-a7ac-1e23a5f149bf","historyId":"d4365c8dc84f5b6057118b05084e3388","fullName":"com.reqres.tests.ReqresApiTests.testGetUserFail","labels":[{"name":"package","value":"com.reqres.tests.ReqresApiTests"},{"name":"testClass","value":"com.reqres.tests.ReqresApiTests"},{"name":"testMethod","value":"testGetUserFail"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"com.reqres.tests.ReqresApiTests"},{"name":"host","value":"DESKTOP-BUGKGO7"},{"name":"thread","value":"232256@DESKTOP-BUGKGO7.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"feature","value":"User Management"},{"name":"story","value":"Get single user details"},{"name":"severity","value":"critical"}],"links":[],"name":"testGetUserFail","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The following asserts failed:\n\tStatus code should be 200 expected [2000] but found [401],\n\tUser ID should be 2 expected [200] but found [2],\n\tEmail should match expected [aajanet.weaver@reqres.in] but found [janet.weaver@reqres.in]","trace":"java.lang.AssertionError: The following asserts failed:\n\tStatus code should be 200 expected [2000] but found [401],\n\tUser ID should be 2 expected [200] but found [2],\n\tEmail should match expected [aajanet.weaver@reqres.in] but found [janet.weaver@reqres.in]\r\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)\r\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)\r\n\tat com.reqres.tests.BaseTest.assertAll(BaseTest.java:23)\r\n\tat com.reqres.tests.ReqresApiTests.testGetUserFail(ReqresApiTests.java:51)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:829)\r\n\tat org.testng.TestRunner.run(TestRunner.java:602)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\r\n\tat org.testng.TestNG.run(TestNG.java:1067)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\r\n"},"stage":"finished","description":"Test to verify retrieving information of a single user FAIL","steps":[],"attachments":[],"parameters":[],"start":1746192639242,"stop":1746192642202}